server:
  port: 8170

spring:
  application:
    name: yhyy-export
  http:
    multipart:
      maxFileSize: 10Mb
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/0903-test
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      initial-size: 20
      max-active: 100
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 'x'
      filters: stat,slf4j
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false


mybatis:
  check-config-location: true                          #配置校验（true/false）
  config-location: classpath:mybatis-config.xml         #mybatis配置文件
  mapper-locations: classpath*:mapper/**/*.xml    #mapper xml配置路径
teststr: cass

ribbon:
  ReadTimeout: 300000              #请求处理的超时时间
  ConnectTimeout: 10000           #ribbon请求连接的超时时间
flag: 0 #1加tddl #0不加


#shop 商品列表 ES读取开关 1 开启 0 关闭
shop_query_es: 1
#shop 相册列表 ES读取开关 1 开启 0 关闭
album_query_es: 1
#shop 图片列表 ES读取开关 1 开启 0 关闭
image_query_es: 1


# 商城订单导出 ES读取开关 1 开启 0 关闭
order_export_es: 1
# 商品订单导出 ES读取开关 1 开启 0 关闭
productOrder_export_es: 1
# 维权订单导出 ES读取开关 1 开启 0 关闭
proOrder_export_es: 1
# 退货退款订单导出 ES读取开关 1 开启 0 关闭
backOrder_export_es: 1
# 待评论订单导出 ES读取开关 1 开启 0 关闭
waitEvaluationOrder_export_es: 1


