server:
  port: 8169
  tomcat:
    max-http-post-size: 800720
spring:
  application:
    name: yhyy-front-admin-2.0
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb
  datasource:
    druid:
      url: jdbc:mysql://localhost:3306/0903-test
      driver-class-name: com.mysql.jdbc.Driver
      username: root
      password: 123456
      initial-size: 20
      max-active: 100
      min-idle: 5
      max-wait: 60000
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000
      validation-query: SELECT 'x'
      filters: stat,slf4j
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false

  thymeleaf:
    cache: false
    check-template-location: true
    content-type: text/html
    enabled: true
    encoding: utf-8
    mode: LEGACYHTML5
    prefix: classpath:/templates
  redis:
    host: localhost
    password:
    port: 6379
    database: 0
    pool:
      max-active: 8
      max-wait: -1
      max-idle: 8
      min-idle: 0
    timeout: 0


eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://localhost:8669/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10

management:
  security:
    enabled: false

mybatis:
  check-config-location: true                          #配置校验（true/false）
  config-location: classpath:mybatis-config.xml         #mybatis配置文件
  mapper-locations: classpath*:mapper/**/*.xml    #mapper xml配置路径
#MQ
mq-suffix: _zt_test
mq-PUSH_TOPIC: yhyy_push
mq-PUSH_PRODUCER_ID: PID_push
mq-PUSH_TAG: PUSHNOTIFICATION
mq-ONSADDR: http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
mq-PRODUCERID_SEARCH: PID_SOLRINDEX
mq-TOPIC_SEARCH: yhyy-search
mq-SEARCH_CONSUMER_ID: CID_SOLRINDEX
# 更新用户信息通知钱包
ac_user_receive_topic: AcUserReceive
ac_user_receive_consumer_id: CID_AcUserReceive
ac_user_receive_producer_id: PID_AcUserReceive
ac_user_receive_tag: AcUserReceiveTag
odr_refund_topic: refund
odr_refund_producer_id: PID_refund
odr_refund_tag: refund_tag
# 商品详情链接地址
productUrl: https://testwww.yuehuayueyou.com/web/shopMall/products/productDetail.html?proId=

#通知
notification:
  link: https://testtm.yuehuayueyou.com/xiangqing

#会员实名认证,身份证验证是否开启
memberIdentity: 1

#上传图片路径
manageName: manage

#极光 true 为开发环境, false 为测试环境
isDevelop: false


ribbon:
  ReadTimeout: 300000              #请求处理的超时时间
  ConnectTimeout: 10000           #ribbon请求连接的超时时间
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 30000


#购物车
cartitem_topic: CartItemUpdate
cartitem_producer_id: PID_CartItemUpdate
cartitem_update_tag: CartItemTag

#是否使用user_approve表
userApproveIsStatus: 0


##极光push 阿里测试
PushAppkey: 5b7140c1dd618c50f8988e59
PushAppmastersecret: 73751abba7120d42df1978fd


person:
  name: dq
  age: 18

##member从ES读取开关 1 开启 0 关闭
memberapprove_query_es: 1
##member从ES读取开关 1 开启 0 关闭
memberfrozen_query_es: 1
##member从ES读取开关 1 开启 0 关闭
mobileupdate_query_es: 1
##member从ES读取开关 1 开启 0 关闭
storeapprove_query_es: 1
##member从ES读取开关 1 开启 0 关闭
storedata_query_es: 1

#shop 商品列表 ES读取开关 1 开启 0 关闭
shop_query_es: 0
#shop 相册列表 ES读取开关 1 开启 0 关闭
album_query_es: 0
#shop 图片列表 ES读取开关 1 开启 0 关闭
image_query_es: 0


# 商城订单 ES读取开关 1 开启 0 关闭
order_query_es: 0
# 商品订单 ES读取开关 1 开启 0 关闭
productOrder_query_es: 0
# 维权订单 ES读取开关 1 开启 0 关闭
proOrder_query_es: 0
# 退货退款订单 ES读取开关 1 开启 0 关闭
backOrder_query_es: 0
# 待评论订单 ES读取开关 1 开启 0 关闭
waitEvaluationOrder_query_es: 0

# 原订单模块ES读取开关，商城订单列表，商品订单列表，维权订单列表
is_query_from_es: 1
