spring:
  application: 
    name: yhyy-pay-job
hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000

management:
  security:
    enabled: false
#service discovery url
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://127.0.0.1:8669/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
server:
  port: 8893
  connection-timeout: 10000 # 连接超时时间
  tomcat:
    max-threads: 60000
    max-connections: 60000
    max-http-post-size: 30720
    accept-count: 20000
    min-spare-threads: 100
