server:
  port: 8172

spring:
  application:
    name: yhyy-export
  http:
    multipart:
      maxFileSize: 10Mb
  datasource:
    druid:
      url: jdbc:mysql://rm-uf61nziquk087s663.mysql.rds.aliyuncs.com:3306/malldb
      driver-class-name: com.mysql.jdbc.Driver
      username: dev_root
      password: ^mDlTEpumFuhyGp!
      #url: jdbc:mysql://drds42g89fs73g0z.drds.aliyuncs.com:3306/drds_bj_scyhyh20180130
      #driver-class-name: com.mysql.jdbc.Driver
      #username: drds_bj_scyhyh20180130
      #password: hFeAiWfv2X8nGu4Z
      initial-size: 20  #初始化连接数
      max-active: 100  #最大连接池数量
      min-idle: 5  #最小连接池数量
      max-wait: 60000  #获取连接时最大等待时间
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000  #连接保持空闲而不被驱逐的最小时间
      validation-query: SELECT 'x'  #用来检测连接是否有效的SQL
      filters: stat,slf4j
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:  #关闭监控页面
        enabled: false
      web-stat-filter:  #关闭采集数据功能
        enabled: false
mybatis:
  check-config-location: true                          #配置校验（true/false）
  config-location: classpath:mybatis-config.xml         #mybatis配置文件
  mapper-locations: classpath*:mapper/**/*.xml    #mapper xml配置路径
teststr: cass

ribbon:
  ReadTimeout: 300000              #请求处理的超时时间
  ConnectTimeout: 10000           #ribbon请求连接的超时时间
flag: 0


#shop 商品列表 ES读取开关 1 开启 0 关闭
shop_query_es: 0
#shop 相册列表 ES读取开关 1 开启 0 关闭
album_query_es: 0
#shop 图片列表 ES读取开关 1 开启 0 关闭
image_query_es: 0

# 商城订单导出 ES读取开关 1 开启 0 关闭
order_export_es: 0
# 商品订单导出 ES读取开关 1 开启 0 关闭
productOrder_export_es: 0
# 维权订单导出 ES读取开关 1 开启 0 关闭
proOrder_export_es: 0
# 退货退款订单导出 ES读取开关 1 开启 0 关闭
backOrder_export_es: 0
# 待评论订单导出 ES读取开关 1 开启 0 关闭
waitEvaluationOrder_export_es: 0