spring:
  application:
    name: yhyy-solr
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
    consumer:
      key-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
      value-serializer: org.apache.kafka.common.serialization.ByteArraySerializer
  datasource:                           # Mabtis数据源，用于主库操作
    druid:
      url: jdbc:mysql://rm-uf61nziquk087s663.mysql.rds.aliyuncs.com:3306/malldb
      driver-class-name: com.mysql.jdbc.Driver
      username: dev_root
      password: ^mDlTEpumFuhyGp!
      initial-size: 20  #初始化连接数
      max-active: 100  #最大连接池数量
      min-idle: 5  #最小连接池数量
      max-wait: 60000  #获取连接时最大等待时间
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 30000  #连接保持空闲而不被驱逐的最小时间
      validation-query: SELECT 'x'  #用来检测连接是否有效的SQL
      filters: stat,slf4j
      test-while-idle: true
      test-on-borrow: false
      test-on-return: false
      stat-view-servlet:  #关闭监控页面
        enabled: false
      web-stat-filter:  #关闭采集数据功能
        enabled: false
  http:
    multipart:
      maxFileSize: 10Mb
      maxRequestSize: 100Mb
  redis:
    host: r-uf658c3018ab0824.redis.rds.aliyuncs.com
    password: dWkSfAIW53CJRLUy
    port: 6379
    database: 0
    timeout: 666
    pool:
      max-active: 2000
      max-wait: 1000
      min-idle: 36
      max-idle: 66
  zipkin:
    base-url: http://172.19.173.3:9666
  sleuth:
    sampler:
      percentage: 1

management:
  security:
    enabled: false

logging:
  level:
    root:  WARN
    com:
      yhyy:
        solr:
          controller: INFO
          MQActivity: INFO
          es:
            service: INFO
            dao: INFO

#service discovery url
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://172.19.173.115:8669/eureka/
  instance:
    hostname: web-12   # 指定该Eureka实例的主机名
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
server:
  port: 9999
#hystrix.command.default.execution.isolation.thread.timeoutInMilliseconds: 10000
ribbon:
  ConnectTimeout: 30000
  ReadTimeout: 60000
  
mybatis:
  check-config-location: true                          #配置校验（true/false）
  config-location: classpath:mybatis-config.xml         #mybatis配置文件
  mapper-locations: classpath*:mapper/readXml/*.xml
elasticsearch.cluster.name: yhyy
elasticsearch.server.arr: 172.19.172.250:9300,172.19.173.0:9300,172.19.173.4:9300
indexName: collectiondemo
MerchantTypeName: Merchant
ProductTypeName: Product
footIndexName: footcollectiondemo
footTypeName: foot
historyIndexName: historycollectiondemo
historyTypeName: history
ONSAddr: http://onsaddr-internet.aliyun.com/rocketmq/nsaddr4client-internet
topicName: yhyy-search_demo
accessKey: LTAIp2gpRJI0gvKu
secretKey: AfhWdaEw5zrIx9d08Z5058J4QCYEnv
consumerId: CID_SOLRINDEX_demo
#1是 可以看不到会员商品 2是查出会员商品
isShow: 2
esUrl: http://172.19.172.250:9200
#1是 屏蔽悦超市 2是放开悦超市
isShowMda: 1