spring:
  application:
    name: yhyy-zuul-job
  redis:
    host: r-uf658c3018ab0824.redis.rds.aliyuncs.com
    password: dWkSfAIW53CJRLUy
    port: 6379
    database: 0
    timeout: 666
    pool:
      max-active: 2000
      max-wait: 1000
      min-idle: 36
      max-idle: 66
eureka:
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://172.19.173.115:8669/eureka/
  instance:
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 10
    prefer-ip-address: true
server:
  port: 8061